### PR TITLE
Improve `style-namespace` helper

### LINKED ISSUE #1: Future of this addon
Hey @webark, I've landed here from https://github.com/ebryn/ember-component-css/issues/355 so you probably know what I'm going to say. :)

I'm trying to migrate my app to Embroider and ember-component-css is currently the biggest obstacle. So it would be great if we could make this addon work and publish at least a basic version of it.

So my question is: how can I help? :) What needs to be done here to make this addon work with Glimmer and Embroider?

Also, I tried to install the most recent version and there are some issues with `ember-cli-styles-colocation@*` dependency, could you please fix that? I'm not sure what was the intention here. :) I tried symlinking https://github.com/webark/ember-cli-styles-collocation but without any luck.

### LINKED ISSUE #5: Generate a manifest
@webark as you requested in #1, I open a new issue on this topic. However, I read the code a bit and I don't understand why the manifest isn't simply:

```js
getOwner(this).lookup(`style:${componentName}`).styleNamespace
```

Isn't this *exactly* what `podNames` used to do in `ember-component-css`? This code seems to do exactly what I need. Is there any problem using that?

### PR DESCRIPTION
**Pull request by boris-petrov**
Fixes #5

cc @webark

As I mentioned in #5 this fixes the issue for me. Please tell me if this is completely wrong and that it should not be used like that.

### CODE REVIEW

**Comment by webark** [comment]
So I think this looks good. The one thing is this is still reliant on https://github.com/webark/ember-cli-styles/blob/4ead8b009e1905a6d8d3469edc7595c57e97b448/packages/namespace/addon/utils/process-style-type.js#L18-L20

I'm not sure what the long-term support, or support in general, is for that API.

**Comment by boris-petrov** [comment]
Well, if it works on Ember 4 right now, it's going to work until at least Ember 5. :smile: We can think what to do when Ember 5 starts approaching. :smiley:

**Comment by webark** [comment]
hahaha!! fair point

**Comment by webark** [comment]
@boris-petrov Left a couple of comments.

Also, could we switch the commits to be conventional commits, and reference the issue number where applicable?

I haven't added a `CONTRIBUTING.md` yet, nor something like husky. But want to keep that format.

**Comment by webark** [comment]
Also, let's add this use case to the acceptance tests.

**Comment by boris-petrov** [comment]
@webark - I changed the commit messages, is this what you mean by "conventional commits" and reference the issue?

I don't see the comments that you've added, where is that?

Also, can you point me where exactly I should add a test? I see only "tests" in the dummy app but I'm not sure how that whole thing works.

**Comment by webark** [comment]
can you not see the three comments attached to lines of the changes in the PR?

**Comment by boris-petrov** [comment]
Nope. Perhaps try adding them again?

**Comment by webark** [comment]
weird. I just "assigned" this to you.. can you see the review comments now?

**Comment by boris-petrov** [comment]
No... can you send me a screenshot of the comments? :smile:

**Review by webark — CHANGES_REQUESTED** [review]

**Comment by webark** [comment]
🤦 I had forgotten to hit submit. sorry @boris-petrov

**Comment by webark** [comment]
And for the test, you can set up a new route in the dummy app, use the differing component name, and then set up an acceptance test to verify it.

Cause that process isn't laid out currently, you could add it to the `unique file name` test for now, and I can split it off later..

https://github.com/webark/ember-cli-styles/blob/1a536fde4e340a4da27c93f98b9c0ceecf28d08f/packages/namespace/tests/acceptance/unique-component-paths-test.js#L11-L15
https://github.com/webark/ember-cli-styles/blob/1a536fde4e340a4da27c93f98b9c0ceecf28d08f/packages/namespace/tests/dummy/app/router.js#L35
https://github.com/webark/ember-cli-styles/blob/1a536fde4e340a4da27c93f98b9c0ceecf28d08f/packages/namespace/tests/dummy/app/unique-component-paths/template.hbs#L1
https://github.com/webark/ember-cli-styles/blob/1a536fde4e340a4da27c93f98b9c0ceecf28d08f/packages/namespace/tests/dummy/app/unique-component-paths/-components/test-component/template.hbs#L1
https://github.com/webark/ember-cli-styles/blob/1a536fde4e340a4da27c93f98b9c0ceecf28d08f/packages/namespace/tests/dummy/app/unique-component-paths/-components/test-component/styles.scss#L2

this is the path of how that test is setup.

**Comment by boris-petrov** [comment]
@webark - I believe I did everything you requested! Thanks for the links for the tests - I wouldn't have figured it out on my own.

I've added a passing test and I've split the other changes in different PRs.

**Review by webark — APPROVED** [review]

**Comment by webark** [comment]
@boris-petrov this has been released. 

```
 - ember-cli-styles-colocation@1.0.0-alpha.4
 - ember-cli-styles-namespace@1.0.0-alpha.7
 - ember-cli-styles-preprocessor@1.0.0-alpha.4
```

**Comment by boris-petrov** [comment]
Thank you!

**Comment by webark** [comment]
Thank you!

**Pull request merged**
