### PR TITLE
feat(preprocessor): updated preprocessor to not include any by default.

### LINKED ISSUE #8: Load PostCSS plugins on demand
I saw that `ember serve` tells me that, in addition to `SassCompiler` which I need, also `LessCompiler` and `StylusCompiler` have run. I don't have any `less` or `stylus` code in my app so it would be nice to not run these compilers.

### PR DESCRIPTION
**Pull request by webark**
All style preprocessors must be manually added in order to process. Will still export the default set defined in https://github.com/webark/ember-cli-styles/blob/9067ae607be0cd2f69b1e650c23833b62cccc97e/packages/preprocessor/lib/preprocessors.js

I moved the preprocessor packages into the dev dependencies, but should they be set as `peerDependencies` or `optionalDependencies` ? I always forget how these work Do you have any familiarity @boris-petrov ?

This should fix #8

### CODE REVIEW

**Comment by boris-petrov** [comment]
I think they should be in `optionalDependencies` as `peerDependencies` are actually *required*.

I didn't understand what you mean by your first paragraph. Should *all* style preprocessors be added for `ember-cli-styles` to work or *only* the ones that an app uses? Also, what is the "default set" used for?

**Comment by webark** [comment]
“All” meaning any number of them. (it’s designed so you can mix and match different styles types). And the default is just if people don’t want to think about it, they could just import that and either just add it all, or add what they want.

**Comment by boris-petrov** [comment]
@webark - is this PR good to go? Does it to what it says it does or it needs more work?

**Comment by webark** [comment]
I'll release this

**Comment by boris-petrov** [comment]
@webark - thanks for merging! I'm awaiting the release so I can test this. :)

**Comment by webark** [comment]
this was released.

**Pull request merged**
